services:
  adminerevo:
    container_name: wp-adminer
    image: ghcr.io/shyim/adminerevo:latest
    restart: unless-stopped
    volumes:
      - /home/mneza/tmp/robostore:/dumps
    networks:
      - wp_be
      - t3_proxy
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.adminer-rtr.entrypoints=websecure"
      - "traefik.http.routers.adminer-rtr.rule=Host(`adminer.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.adminer-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.adminer-rtr.service=adminer-svc"
      - "traefik.http.services.adminer-svc.loadbalancer.server.port=8080"
