services:
  robostore-nginx:
    image: nginx:1.27.2
    container_name: robostore-nginx
    restart: unless-stopped
    networks:
      - wp_be
      - t3_proxy
    volumes:
      - $WP_DIR/html:/var/www/html
      - $NGINX_CONF:/etc/nginx/conf.d/default.conf
      - $NGINX_LOGS:/var/log/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp-rtr.entrypoints=websecure"
      - "traefik.http.routers.wp-rtr.rule=Host(`$DOMAINNAME`)"
      - "traefik.http.routers.wp-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.wp-rtr.service=wp-svc"
      - "traefik.http.services.wp-svc.loadbalancer.server.port=80"
